### ISSUE TITLE
No custom template argument support

### ISSUE THREAD

**Issue by nabijaczleweli** [Anmol-Singh-Jaggi/Pretty-print#4]
Say if I had something like this:

``` c++
  class mlg_pro_360_noscope;                     // Defined elsewhere
  class my_super_mlg_pro_360_noscope_allocator;  // Defined elsewhere
  int main() {
    std::vector<mlg_pro_360_noscope, my_super_mlg_pro_360_noscope_allocator> vec;
    /// Add stuff to `vec` somehow here ///
    std::cout << vec << '\n';
  }
```

It would give me an error, since your `operator<<()`s accept `const std::vector<T, std::allocator<T>> &` only.
Note, that this applies for all other `std` containers as well

**Comment by Anmol-Singh-Jaggi** [comment]
@nabijaczleweli I am aware of that. But since, I mostly do not use any custom allocators for any of my classes, I do not want to unnecessarily complicate the code.
